---
copyright: Copyright &copy; 2025, me
edit_uri: edit/main/docs
repo_name: UCL-ARC/rsd-summerschool
repo_url: https://github.com/UCL-ARC/rsd-summerschool
site_author: me
site_name: Average Squares

extra:
  generator: false
  icon:
    edit: material/pencil
    repo: fontawesome/brands/github
    view: material/eye

nav:
  - Home: index.md
  - Contents:
      - contents/average-squares-doc.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: .
          options:
            docstring_style: numpy
            show_root_heading: true
            show_signature_annotations: true
            show_source: true
  - search

theme:
  features:
    - navigation.sections
    - navigation.tabs
    - toc.integrate 
  name: material
  palette:
    # palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

validation:
  absolute_links: warn
  omitted_files: warn
  unrecognized_links: warn
